"""Proof harness: evidence that the runtime does what HOMER-1 claims.

This is deliberately *not* a single-case echo test. It proves four things that a
tautology cannot fake:

  1. Generative engineering — the Factory emits validated, compilable source code,
     not hand-written calculators (we open the persisted artifact and run it).
  2. Stateful acceleration — a second run *reuses* what the first generated;
     engineering steps are saved, not repeated.
  3. Recursive validation — Analyze iterates to a fixed point.
  4. Differentiated routing — a high-risk, a low-risk, and a missing-data case are
     routed to *different* dispositions (the system reasons, it does not rubber-stamp).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .factory import compile_tool
from .memory import InstitutionalMemory
from .runtime import run
from .schemas import Judgment, KnowledgeLayer, Lesson, PatientCase, RuntimeResult, RuntimeState


@dataclass(frozen=True)
class Criterion:
    id: str
    state: str
    claim: str
    evidence_path: str
    passed: bool
    evidence: Any


def _step(result: RuntimeResult, state: RuntimeState):
    return next((s for s in result.trace if s.state == state), None)


def _c(id, state, claim, evidence_path, passed, evidence) -> Criterion:
    return Criterion(id=id, state=state, claim=claim, evidence_path=evidence_path, passed=bool(passed), evidence=evidence)


def prove_case(case: PatientCase, memory_dir: Path) -> dict[str, Any]:
    """Prove the full runtime on a single case, including generate-then-reuse.

    `memory_dir` should be empty/fresh: run 1 generates the toolchain, run 2 reuses
    it. That pair is the acceleration curve, demonstrated in one artifact.
    """
    memory = InstitutionalMemory(memory_dir)

    first = run(case, memory=memory)   # generates the instruments
    second = run(case, memory=memory)  # reuses them

    factory = _step(first, RuntimeState.FACTORY)
    plan = _step(first, RuntimeState.PLAN)
    analyze = _step(first, RuntimeState.ANALYZE)
    simulate = _step(first, RuntimeState.SIMULATE)
    output = _step(first, RuntimeState.OUTPUT)

    instrument_names = {i.name for i in first.instruments}
    score_names = {s.name for s in first.scores}
    scenario_names = {s.name for s in first.scenarios}

    # Open a persisted tool artifact and actually execute it — proof the Factory
    # produced runnable code, not a description of code.
    tool_path = memory.tools_dir / "frailty_index_calculator@0.2.0.py"
    generated_source = tool_path.read_text(encoding="utf-8") if tool_path.exists() else ""
    executes = False
    if generated_source:
        try:
            fn = compile_tool(generated_source)
            value, _ = fn({"age": 82, "mobility.current_mobility_drop": "moderate", "mobility.falls_last_6_months": 1, "mobility.nutrition_risk": "high", "prior_admissions_6_months": 2})
            executes = abs(value - 0.8) < 1e-6
        except Exception:
            executes = False

    criteria = [
        _c(
            "factory.generative-source",
            "factory",
            "The Factory generates validated, executable instrument source code (not hand-written calculators).",
            "memory/tools/*.py",
            "def score(values):" in generated_source and "Auto-generated by the HOMER-1 Factory" in generated_source and executes,
            {"artifact": "frailty_index_calculator@0.2.0.py", "compiles_and_matches_reference": executes, "first_120_chars": generated_source[:120]},
        ),
        _c(
            "factory.validation-declarations",
            "factory",
            "Every instrument declares validation checks and limitations before use.",
            "instruments[*].validation_checks + limitations",
            all(i.validation_checks and i.limitations for i in first.instruments),
            [{"name": i.name, "validation_checks": i.validation_checks, "limitations": i.limitations} for i in first.instruments],
        ),
        _c(
            "factory.stateful-acceleration",
            "factory",
            "A second run reuses what the first generated — institutional memory makes the next case cheaper.",
            "result.factory_report",
            first.factory_report.engineering_steps_this_run == 3
            and first.factory_report.tools_reused == []
            and second.factory_report.engineering_steps_this_run == 0
            and second.factory_report.engineering_steps_saved == 3,
            {"run1": first.factory_report.model_dump(mode="json"), "run2": second.factory_report.model_dump(mode="json")},
        ),
        _c(
            "plan.trace-decomposition",
            "plan",
            "Plan decomposes the discharge decision into auditable clinical, operational, and support checks.",
            "trace[plan].outputs",
            plan is not None
            and len(plan.outputs) >= 6
            and any("afebrile" in i.lower() for i in plan.outputs)
            and any("medication access" in i.lower() for i in plan.outputs),
            plan.outputs if plan else None,
        ),
        _c(
            "analyze.deterministic-probabilistic-fusion",
            "analyze",
            "Analyze fuses generated rules into explainable, bounded, banded patient-level findings.",
            "result.scores[*]",
            {"frailty_index", "secondary_infection_risk", "environmental_medication_access_risk"}.issubset(score_names)
            and all(0 <= s.value <= 1 for s in first.scores)
            and all(s.band in {"low", "moderate", "high"} for s in first.scores),
            [s.model_dump(mode="json") for s in first.scores],
        ),
        _c(
            "analyze.recursive-validation-loop",
            "analyze",
            "Recursive validation iterates to a fixed point and catches borderline/high-risk signals.",
            "trace[analyze].checks + analyze_iterations",
            analyze is not None
            and first.analyze_iterations >= 1
            and any("force clinician_review_required" in c for c in analyze.checks)
            and any("pending cultures" in c for c in analyze.checks),
            {"iterations": first.analyze_iterations, "checks": analyze.checks if analyze else None},
        ),
        _c(
            "simulate.whatif-operations",
            "simulate",
            "Simulate evaluates discharge timing and support alternatives with explicit operational triggers.",
            "result.scenarios[*]",
            {"discharge_today_no_added_support", "delay_24h_reassess", "discharge_with_medication_and_home_support"}.issubset(scenario_names)
            and all(s.operational_trigger for s in first.scenarios)
            and any(s.readmission_risk_delta > 0 for s in first.scenarios)
            and any(s.readmission_risk_delta < 0 for s in first.scenarios),
            [s.model_dump(mode="json") for s in first.scenarios],
        ),
        _c(
            "simulate.empathy-with-guardrails",
            "simulate",
            "What-if image prompts drive discharge empathy without becoming clinical evidence.",
            "result.scenarios[*].empathy_prompt + trace[simulate].checks",
            simulate is not None
            and all(s.empathy_prompt for s in first.scenarios)
            and any("non-authoritative" in c for c in simulate.checks)
            and any("No fear tactics" in s.empathy_prompt or "No identifiable" in s.empathy_prompt for s in first.scenarios),
            {"prompts": [s.empathy_prompt for s in first.scenarios], "checks": simulate.checks if simulate else None},
        ),
        _c(
            "output.decision-ready-human-handoff",
            "output",
            "Output produces a decision-ready human handoff with red flags, actions, and mandatory clinician review.",
            "result.handoff",
            output is not None
            and first.handoff.required_human_review is True
            and first.handoff.disposition == "clinician_review_required"
            and bool(first.handoff.red_flags)
            and bool(first.handoff.actions_to_consider)
            and "clinician sign-off required" in output.checks,
            first.handoff.model_dump(mode="json"),
        ),
        _c(
            "persist.institutional-memory",
            "persist",
            "The run persists institutional memory for pulmonary service-line reuse, not just a one-off answer.",
            "memory/manifest.jsonl",
            first.institutional_memory_event.get("service_line") == "pulmonary"
            and first.institutional_memory_event.get("domain") == "pneumonia_discharge"
            and "copd_flare_up" in first.institutional_memory_event.get("future_reuse_targets", [])
            and memory.tool_count() == 3
            and memory.runs_completed() == 2,
            {"event": second.institutional_memory_event, "tools_in_memory": memory.tool_count(), "runs": memory.runs_completed()},
        ),
        _c(
            "governance.synthetic-safety-boundary",
            "governance",
            "The use case preserves synthetic-only safety boundaries and avoids autonomous clinical orders.",
            "instrument.limitations + handoff.clinician_note + memory_event.note",
            all(any("Synthetic" in l or "validated" in l for l in i.limitations) for i in first.instruments)
            and "must validate" in first.handoff.clinician_note
            and "Do not store PHI" in first.institutional_memory_event.get("note", ""),
            {"clinician_note": first.handoff.clinician_note, "memory_note": first.institutional_memory_event.get("note")},
        ),
        _c(
            "runtime.governed-state-order",
            "runtime",
            "Runtime executes the governed HOMER-1 state order before persistence.",
            "result.trace[*].state",
            [s.state.value for s in first.trace] == ["factory", "plan", "analyze", "simulate", "output"],
            [s.state.value for s in first.trace],
        ),
    ]

    payload = [
        {"id": c.id, "state": c.state, "claim": c.claim, "evidence_path": c.evidence_path, "passed": c.passed, "evidence": c.evidence}
        for c in criteria
    ]
    passed = all(c.passed for c in criteria)
    return {
        "case_id": case.patient_id,
        "framework": "HOMER-1-inspired governed clinical reasoning runtime",
        "passed": passed,
        "criteria_passed": sum(1 for c in criteria if c.passed),
        "criteria_total": len(criteria),
        "criteria": payload,
        "result": first.model_dump(mode="json"),
    }


def prove_cohort(cases: list[PatientCase], memory_dir: Path) -> dict[str, Any]:
    """Prove differentiated routing + compounding memory across a real cohort.

    All cases share ONE institutional memory. The first case generates the
    toolchain; every subsequent case reuses it. Dispositions must differ by risk.
    """
    memory = InstitutionalMemory(memory_dir)
    results = [run(c, memory=memory) for c in cases]

    by_id = {r.patient_id: r for r in results}
    dispositions = {r.patient_id: r.handoff.disposition for r in results}
    distinct = len(set(dispositions.values()))

    first = results[0]
    rest = results[1:]

    criteria = [
        _c(
            "cohort.generate-once",
            "factory",
            "The first case in a fresh service line generates the toolchain.",
            "results[0].factory_report",
            first.factory_report.engineering_steps_this_run == 3 and first.factory_report.tools_reused == [],
            first.factory_report.model_dump(mode="json"),
        ),
        _c(
            "cohort.reuse-thereafter",
            "factory",
            "Every later case reuses the generated toolchain (zero re-engineering).",
            "results[1:].factory_report",
            all(r.factory_report.engineering_steps_this_run == 0 and r.factory_report.engineering_steps_saved == 3 for r in rest),
            [r.factory_report.model_dump(mode="json") for r in rest],
        ),
        _c(
            "cohort.differentiated-routing",
            "output",
            "Distinct-risk cases route to distinct dispositions — the system reasons, it does not rubber-stamp.",
            "results[*].handoff.disposition",
            distinct >= 2,
            dispositions,
        ),
        _c(
            "cohort.human-review-always",
            "governance",
            "Every disposition still requires human review.",
            "results[*].handoff.required_human_review",
            all(r.handoff.required_human_review for r in results),
            {r.patient_id: r.handoff.required_human_review for r in results},
        ),
        _c(
            "cohort.single-toolset",
            "persist",
            "The whole cohort is served by one persisted, versioned toolset in memory.",
            "memory.tool_count()",
            memory.tool_count() == 3 and memory.runs_completed() == len(cases),
            {"tools_in_memory": memory.tool_count(), "runs": memory.runs_completed()},
        ),
    ]

    payload = [
        {"id": c.id, "state": c.state, "claim": c.claim, "evidence_path": c.evidence_path, "passed": c.passed, "evidence": c.evidence}
        for c in criteria
    ]
    return {
        "cohort_size": len(cases),
        "passed": all(c.passed for c in criteria),
        "criteria_passed": sum(1 for c in criteria if c.passed),
        "criteria_total": len(criteria),
        "dispositions": dispositions,
        "criteria": payload,
        "results": {pid: by_id[pid].model_dump(mode="json") for pid in by_id},
    }


def prove_collector(cases_with_scripts: list[tuple[PatientCase, list[Judgment], Lesson | None]], memory_dir: Path) -> dict[str, Any]:
    """Prove the institutional-knowledge collector end to end.

    Runs a scripted multi-case conference sharing one memory and proves the
    payoff: a binary eval suite is produced, preference pairs are emitted where
    the room overturns the tool, alignment is computed per layer, and durable
    teaching artifacts persist.
    """
    from .evals import build_eval_cases, build_preference_pairs
    from .export import build_bundle
    from .session import finalize_case, present, start_session

    memory = InstitutionalMemory(memory_dir)
    session = start_session("proof-session", [c.patient_id for c, _, _ in cases_with_scripts])

    overturns = 0
    for case, judgments, lesson in cases_with_scripts:
        runtime = present(case, memory)
        finalize_case(memory, session, case, runtime, judgments, lesson, KnowledgeLayer.SERVICE_LINE)
        memory.record_eval_cases(build_eval_cases(runtime, judgments, KnowledgeLayer.SERVICE_LINE))
        prefs = build_preference_pairs(runtime, judgments, lesson, KnowledgeLayer.SERVICE_LINE)
        memory.record_preferences(prefs)
        overturns += sum(1 for j in judgments if j.consensus == "fail")

    bundle = build_bundle(memory)
    alignment = {a["knowledge_layer"]: a for a in bundle["alignment"]}

    criteria = [
        _c("collector.binary-eval-suite", "evals",
           "The conference produces a binary eval suite (one case per judged step).",
           "memory/evals.jsonl",
           bundle["counts"]["eval_cases"] == 3 * len(cases_with_scripts),
           bundle["counts"]),
        _c("collector.preference-on-overturn", "evals",
           "Preference pairs are emitted wherever the room overturns the tool.",
           "memory/preferences.jsonl",
           bundle["counts"]["preference_pairs"] >= overturns and overturns > 0,
           {"preference_pairs": bundle["counts"]["preference_pairs"], "overturns": overturns}),
        _c("collector.judge-alignment", "evals",
           "Judge alignment (TPR/TNR + outcome agreement) is computed, with an overall roll-up.",
           "alignment[*]",
           "overall" in alignment and alignment["overall"]["n"] == len(cases_with_scripts),
           alignment.get("overall")),
        _c("collector.durable-artifacts", "persist",
           "Durable teaching artifacts (lessons, case studies) persist to institutional memory.",
           "memory/lessons.jsonl + case_studies.jsonl",
           bundle["counts"]["lessons"] >= 1 and bundle["counts"]["case_studies"] == len(cases_with_scripts),
           bundle["counts"]),
        _c("collector.knowledge-chain-tagged", "governance",
           "Every exported artifact is tagged to a knowledge-chain layer.",
           "eval_suite_jsonl",
           all('"knowledge_layer"' in line for line in bundle["eval_suite_jsonl"].splitlines() if line.strip()),
           {"sample": bundle["eval_suite_jsonl"].splitlines()[:1]}),
    ]

    payload = [
        {"id": c.id, "state": c.state, "claim": c.claim, "evidence_path": c.evidence_path, "passed": c.passed, "evidence": c.evidence}
        for c in criteria
    ]
    return {
        "passed": all(c.passed for c in criteria),
        "criteria_passed": sum(1 for c in criteria if c.passed),
        "criteria_total": len(criteria),
        "criteria": payload,
        "bundle_counts": bundle["counts"],
        "alignment": bundle["alignment"],
    }
